/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * telaUsuarios.java
 *
 * Created on Mar 23, 2013, 5:39:04 PM
 */
package tela;

import atualizaTabelas.AtualizaTabelaUsuario;
import controle.ControleUsuario;
import javax.swing.JTable;
import minhasTabelas.*;
import utilidades.Funcoes;

/**
 *
 * @author marcelojtelles
 */
public class TelaUsuarios extends javax.swing.JInternalFrame {
    public static String idConsultado;
    int pergunta;
    public static JTable table;
    public static int ini,iniInterno,fim;
    public static String consulta=null;

    
    /** Creates new form telaUsuarios */
    public TelaUsuarios() {
        initComponents();
        //funcoes.reloadUsuarios(this);  
        ini = 0;
        fim = atualizaTabelas.AtualizaTabelaUsuario.items;
        iniInterno=0;
        consulta="";
        table = AtualizaTabelaUsuario.atualizaUsuarioPag(this,ini,fim,consulta);     
        jScrollPane1.setViewportView(table); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        btnPrimeiro = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        cmbIr = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblPagina = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnIr = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Completo", "Usuário", "Data Cadastro"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(29, 119, 571, 240);

        jLabel1.setText("Buscar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(76, 26, 107, 16);

        jButton1.setText("ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 10, 75, 35);

        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyReleased(evt);
            }
        });
        getContentPane().add(txtBusca);
        txtBusca.setBounds(193, 6, 231, 40);

        btnPrimeiro.setText("<<");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrimeiro);
        btnPrimeiro.setBounds(29, 375, 75, 25);

        btnUltimo.setText(">>");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        getContentPane().add(btnUltimo);
        btnUltimo.setBounds(528, 375, 75, 25);

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnterior);
        btnAnterior.setBounds(110, 375, 75, 25);

        btnProximo.setText(">");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        getContentPane().add(btnProximo);
        btnProximo.setBounds(447, 375, 75, 25);

        getContentPane().add(cmbIr);
        cmbIr.setBounds(233, 375, 90, 25);

        jButton6.setText("Novo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(29, 50, 210, 35);

        jButton7.setText("Fechar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(343, 50, 260, 35);

        lblTotal.setText("0");
        getContentPane().add(lblTotal);
        lblTotal.setBounds(100, 410, 80, 25);

        lblPagina.setText("0");
        getContentPane().add(lblPagina);
        lblPagina.setBounds(440, 410, 160, 25);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Total:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 410, 70, 25);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Página:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 410, 70, 25);

        btnIr.setText("ir");
        btnIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrActionPerformed(evt);
            }
        });
        getContentPane().add(btnIr);
        btnIr.setBounds(330, 375, 60, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    // TODO add your handling code here:
    TelaUsuariosDetalhe t;
    t = new TelaUsuariosDetalhe();
    TelaPrincipal.telaTrabalho.add(t);
    t.setVisible(true);
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    // TODO add your handling code here:
    this.setVisible(false);
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    consulta = txtBusca.getText();
    table = AtualizaTabelaUsuario.atualizaUsuarioPag(this,0,atualizaTabelas.AtualizaTabelaUsuario.items,consulta);     
    jScrollPane1.setViewportView(table);        
}//GEN-LAST:event_jButton1ActionPerformed

private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
    // TODO add your handling code here:
    //para avançar, basta colocar 10 a mais no ini e no fim
    ini = ini + atualizaTabelas.AtualizaTabelaUsuario.items;
    fim = fim + atualizaTabelas.AtualizaTabelaUsuario.items;
    table = AtualizaTabelaUsuario.atualizaUsuarioPag(this,ini,fim,consulta);     
    jScrollPane1.setViewportView(table); 
}//GEN-LAST:event_btnProximoActionPerformed

private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
    // TODO add your handling code here:
    //para retroceder, basta decrementar 10 no ini e no fim
    ini = ini - atualizaTabelas.AtualizaTabelaUsuario.items;
    fim = fim - atualizaTabelas.AtualizaTabelaUsuario.items;
    table = AtualizaTabelaUsuario.atualizaUsuarioPag(this,ini,fim,consulta);     
    jScrollPane1.setViewportView(table); 
}//GEN-LAST:event_btnAnteriorActionPerformed

private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
    // TODO add your handling code here:
    //para ir na ultima página deve fazer um cálculo.
    //o fim é fácil, basta colocar nele a quantidade de registros.
    //o ini é um pouco diferente, precisamos colocar nele o seguinte:
    //pegue a quantidade de registros e divida pela quantidade de itens por página:
    //Exemplo se temos 39 vamos dividir o 39 por 10, teremos 3 como resultado
    //agora multiplicamos o 3 pela quantidade de regoistros e obtivemos o 30! sempre funciona...
    int quantosTem;
    ControleUsuario u = new ControleUsuario();
    quantosTem = u.quantosU(txtBusca.getText());
    
    ini = (quantosTem/atualizaTabelas.AtualizaTabelaUsuario.items)*atualizaTabelas.AtualizaTabelaUsuario.items;
    fim = quantosTem;
    table = AtualizaTabelaUsuario.atualizaUsuarioPag(this,ini,fim,consulta);     
    jScrollPane1.setViewportView(table); 
}//GEN-LAST:event_btnUltimoActionPerformed

private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
    // TODO add your handling code here:
    //para ir na primeira página, basta colocar o 0 no ini e 10 no fim
    ini = 0;
    fim = atualizaTabelas.AtualizaTabelaUsuario.items;
    table = AtualizaTabelaUsuario.atualizaUsuarioPag(this,ini,fim,consulta);     
    jScrollPane1.setViewportView(table);
}//GEN-LAST:event_btnPrimeiroActionPerformed

private void btnIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrActionPerformed
    // TODO add your handling code here:
    ini = ((Integer.parseInt(cmbIr.getSelectedItem().toString())-1)*atualizaTabelas.AtualizaTabelaUsuario.items);
    fim = ((Integer.parseInt(cmbIr.getSelectedItem().toString())-1)*atualizaTabelas.AtualizaTabelaUsuario.items)+atualizaTabelas.AtualizaTabelaUsuario.items;
    table = AtualizaTabelaUsuario.atualizaUsuarioPag(this,ini,fim,consulta);     
    jScrollPane1.setViewportView(table);
}//GEN-LAST:event_btnIrActionPerformed

    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyReleased
        // TODO add your handling code here:
        consulta = txtBusca.getText();
        table = AtualizaTabelaUsuario.atualizaUsuarioPag(this,0,atualizaTabelas.AtualizaTabelaUsuario.items,consulta);     
        jScrollPane1.setViewportView(table);
        txtBusca.grabFocus();
    }//GEN-LAST:event_txtBuscaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnIr;
    public static javax.swing.JButton btnPrimeiro;
    public static javax.swing.JButton btnProximo;
    public static javax.swing.JButton btnUltimo;
    public static javax.swing.JComboBox cmbIr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JLabel lblPagina;
    public static javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
